version: '3'
services:
    mongo:
        image: cmad-mongo
        volumes:
            - ${data_dir}/mongo:/data/db
            - ${data_dir}/mongo-configdb:/data/configdb
        ports:
            - "27017:27017"
    mysql:
        image: cmad-mysql
        volumes:
            - ${data_dir}/mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
        ports:
            - "3306:3306"
           
    #cmad:
    #   image: cmad
    #    container_name: cmad
     #   volumes:
      #      - /opt/maglev:/opt/maglev
       #     - ${HOME}/work:/work
        #    - ${HOME}/.m2:/root/.m2
        #    - ${HOME}/.gradle:/root/.gradle
        #ports:
         #     - "8080:8080"
